openapi: 3.0.3
info:
  title: WASAPhoto API
  description: API for WASAPhoto, a webapp for sharing photos.
  version: 2.1.0
  
  
servers:
  - url: http://localhost:3000
    description: For development purposes
    

security:
  - UsernameAuth: [] 
    
    
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      security: []
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/Username"
        required: true
      
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    $ref: "#/components/schemas/UniqueID"
                    
        '204':
          description: User already logged-in
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '500': { $ref: "#/components/responses/InternalServerError" }
      
  /photos:
    get:
      summary: Get a stream of photos
      description: Retrieve photos in reverse chronological order from followed users.
      operationId: getMyStream
      parameters:
        - name: page
          in: query
          required: true
          description: |
            The next nth range (0-10) of photos retrieved in reverse choronological
            order.
          schema:
            type: integer
            minimum: 1
            example: 1
      
      responses:
        '200':
          description: A list of photos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Photo"
        
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }
              
  /photos/{photoId}:
    parameters:
      - $ref: "#/components/parameters/PhotoID"
    get:
      summary: Get details of a specific photo
      description: Retrieve details of a specific photo.
      operationId: getPhoto
      responses:
        '200':
          description: Details of the photo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Photo"
        
        '404':
          description: Photo not found
        
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /photos/{photoId}/like/{userId}:
    parameters:
      - $ref: "#/components/parameters/PhotoID"
      - $ref: "#/components/parameters/UserID"
          
    put:
      summary: Like a photo
      description: Like a specific photo.
      operationId: likePhoto
      responses:
        '200':
          description: Photo liked successfully
          
        '204':
          description: Photo already liked
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }
          
    delete:
      summary: Unlike a photo
      description: Unlike a liked photo
      operationId: unlikePhoto
    
      responses:
        '200':
          description: Photo unliked successfully
          
        '204':
          description: Photo already unliked
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /photos/{photoId}/comment:
    parameters:
      - $ref: "#/components/parameters/PhotoID"
      
    get:
      summary: Get comments
      description: Get a list of all comments under the photo
      operationId: getComments
      
      responses:
        '200': 
          description: A list of comments
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/Comment"
                  
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }
                  
    post:
      summary: Add a comment to a photo
      description: Add a comment to a specific photo.
      operationId: commentPhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Comment"
              
      responses:
        '201':
          description: Comment added successfully
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /photos/{photoId}/comment/{commentId}:
    parameters:
      - $ref: "#/components/parameters/PhotoID"
      - name: commentId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UniqueID"
      
    delete:
      summary: Remove a comment from a photo
      description: |
        Remove a comment from a specific photo provided that you are the author
        of the photo under which the comment lies.
      operationId: uncommentPhoto
      
      responses:
        '200':
          description: Comment removed successfully
        
        '404': 
          description: Comment not found
        
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }
      
  /users:
    get:
      summary: Search for user profiles
      description: Search for user profiles by username.
      operationId: searchUser
      parameters:
        - name: username
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/Username"
      responses:
        '200':
          description: List of matching user profiles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        
        '404':
          description: No matches have been found
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }
  
  /users/{username}:
    parameters:
      - $ref: "#/components/parameters/Username"
      
    get:
      summary: Get user profile
      description: Retrieve details of a user's profile.
      operationId: getUserProfile
      
      responses:
        '200':
          description: User profile details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        
        '404':
          description: User not found
        
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }
  
  
  /users/{userId}/followings:
    parameters:
      - $ref: "#/components/parameters/UserID"
      
    get:
      summary: Get followings
      description: Get a list of followings
      operationId: getFollowings
      
      responses:
        '200':
          description: List of user profiles 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }
      
      
  /users/{userId}/followings/{username}:
    parameters:
      - $ref: "#/components/parameters/UserID"
      - $ref: "#/components/parameters/Username"
      
    put:
      summary: Follow a user
      description: Follow a specific user.
      operationId: followUser
  
      responses:
        '201':
          description: User followed successfully
        
        '200':
          description: User already followed
        
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }
      
    delete:
      summary: Unfollow a user
      description: Unfollow a specific user.
      operationId: unfollowUser
      
      responses:
        '201':
          description: User unfollowed successfully
        
        '200':
          description: User already unfollowed
        
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/banned:
    parameters:
      - $ref: "#/components/parameters/UserID"
    
    get:
      summary: Get banned users
      description: Get a list of banned users
      operationId: getBannedUsers
      
      responses:
        '200':
          description: List of user profiles 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }
      

  /users/{userId}/banned/{username}:
    parameters:
      - $ref: "#/components/parameters/UserID"
      - $ref: "#/components/parameters/Username"
      
    put:
      summary: Ban a user
      description: Ban a specific user.
      operationId: banUser
      
      responses:
        '201':
          description: User banned successfully
        
        '200':
          description: User already banned
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }
      
    delete:
      summary: Unban a user
      description: Unban a specific user.
      operationId: unbanUser
      
      responses:
        '200':
          description: User unbanned successfully
        
        '204':
          description: User already unbanned
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/change-username:
    parameters:
      - $ref: "#/components/parameters/UserID"
      
    post:
      summary: Change username
      description: Change the username of the authenticated user.
      operationId: setMyUserName
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newUsername:
                  $ref: "#/components/schemas/Username"
              required:
                - newUsername
  
      responses:
        '200':
          description: Username changed successfully
          
        '204':
          description: Username typed is the similar to the former one
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/photo:
    parameters:
      - $ref: "#/components/parameters/UserID"
      
    get:
      summary: Get user's photos
      description: Get a list of photos posted by the authenticated user
      operationId: getMyPhotos
      
      responses:
        '200':
          description: List of user profiles 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Photo"
          
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '500': { $ref: "#/components/responses/InternalServerError" }
      
    post:
      summary: Upload a photo
      description: | 
        Upload a photo for the authenticated user. Once submitted the server uploads the photo
        to a dedicated server/website and attaches a new id, author's username, date, time, 
        and initiates likesAmount and commentsAmount to 0.
        
      operationId: uploadPhoto
      requestBody:
        required: true
        content:
          image/png:
            schema:
              description: Photo to be uploaded as .png file
              type: string
              format: binary
      responses:
        '201':
          description: Photo uploaded successfully
        
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}/photo/{photoId}:
    parameters:
      - $ref: "#/components/parameters/UserID"
      - $ref: "#/components/parameters/PhotoID"
      
    delete:
      summary: Remove a photo
      description: Remove a specific photo for the authenticated user.
      operationId: deletePhoto
      
      responses:
        '200':
          description: Photo removed successfully
        
        '404':
          description: Photo not found
        
        '400': { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Unauthorized" }
        '403': { $ref: "#/components/responses/Forbidden" }
        '500': { $ref: "#/components/responses/InternalServerError" }

        
  
components:

  securitySchemes:
    UsernameAuth:
      type: http
      scheme: bearer
      
      
  parameters:
    PhotoID:
      schema:
        $ref: "#/components/schemas/UniqueID"
      name: photoId
      in: path
      required: true
      description: Photo ID
    
    UserID:
      schema:
        $ref: "#/components/schemas/UniqueID"
      name: userId
      in: path
      required: true
      description: User ID
      
    Username:
      schema:
        $ref: "#/components/schemas/Username"
      name: username
      in: path
      required: true
      description: Username
      
      
  responses:
    BadRequest:
      description: The request was not compliant with the documentation (eg. missing fields, etc)
  
    Unauthorized:
      description: The access token is missing or invalid
      
    Forbidden:
      description: You do not have access rights to the operation
      
    InternalServerError:
      description: The server encountered an internal error. Further info in server logs
      
      
  schemas:
    UniqueID:
      description: UniqueID for any object needed
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      minLength: 36
      maxLength: 36
      readOnly: true
      example: "550e8400-e29b-41d4-a716-446655440000"
      
    Username:
      type: string
      example: Maria
      pattern: 'ˆ.*?$'
      minLength: 3
      maxLength: 32 
    
    ImageURL:
      description: URL of an image
      type: string
      minLength: 10
      maxLength: 256
      readOnly: true
      example: "https://example.com/photo1.jpg"
      
    Timestamp:
      description: Date and time representation
      type: string
      format: date-time
      example: "2023-01-01T12:00:00Z"
      minLength: 20
      maxLength: 20
      readOnly: true
      
    Amount:
      description: Representation of an amount of things of interest
      type: integer
      minimum: 0
      example: 42
      readOnly: true
    
    User:
      description: a user profile containg username, amount of photos, followers and followings
      type: object
      properties:
        userID: 
          $ref: "#/components/schemas/UniqueID"
        username: 
          $ref: "#/components/schemas/Username"
        totalPhotos:
          $ref: "#/components/schemas/Amount"
        follwersAmount:
          $ref: "#/components/schemas/Amount"
        follwingsAmount:
          $ref: "#/components/schemas/Amount"
      
    Photo:
      description: | 
        A photo exists in a separate server or a website such as example.com.
        Once a stream of photos or a photo is requested they should be requested by a 
        host via GET method. 

      type: object
      properties:
        PhotoID: 
          $ref: "#/components/schemas/UniqueID"
        author: 
          $ref: "#/components/schemas/Username"
        imageUrl: 
          $ref: "#/components/schemas/ImageURL"
        timestamp:
          $ref: "#/components/schemas/Timestamp"
        likesAmount:
          $ref: "#/components/schemas/Amount"
        commentsAmount:
          $ref: "#/components/schemas/Amount"
          
    Comment:
      description: Representation of a single comment
      type: object
      properties:
        commentID:
          $ref: "#/components/schemas/UniqueID"
        author: 
          $ref: "#/components/schemas/Username"
        timestamp:
          $ref: "#/components/schemas/Timestamp"
        commentText:
          type: string
          example: "You look good, my man :)"
      required:
        - commentText  
